version: '3.8'

services:
  app:
    build: backend/.
    command:
      bash -c "python manage.py loadall &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: skymarket
      POSTGRES_PASSWORD: skymarket
      POSTGRES_DB: skymarket
    restart: always
    ports:
    - "5555:5432"

  frontend:
    build: frontend/.
    volumes:
      - frontend:/app/build
    depends_on:
      - db
      - app
  nginx:
    image: nginx:1.19.3
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ../backend/media/:/usr/share/nginx/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - db
      - frontend

volumes:
  postgres_data:  
  frontend: